### ISSUE TITLE
Payconiq transaction problem

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#499] opened 2018-05-23 12:15 UTC
```
2018-05-23 14:13:24.290 CEST
Request identity: bart@mobicage.com:be-loc (ios) (/base/data/home/apps/e~rogerthat-server/20180518t124001.409804319394300144/rogerthat/rpc/users.py:145)

2018-05-23 14:13:24.359 CEST
Unhandled payments error (/base/data/home/apps/e~rogerthat-server/20180518t124001.409804319394300144/add_1_monkey_patches.py:127)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20180518t124001.409804319394300144/rogerthat/api/payment.py", line 160, in _do_call
    result = call(app_user, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180518t124001.409804319394300144/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180518t124001.409804319394300144/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180518t124001.409804319394300144/rogerthat/bizz/payment/__init__.py", line 347, in create_transaction
    return get_api_module(provider_id).create_transaction(app_user, params)
  File "/base/data/home/apps/e~rogerthat-server/20180518t124001.409804319394300144/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180518t124001.409804319394300144/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180518t124001.409804319394300144/rogerthat/bizz/payment/providers/payconiq/api.py", line 262, in create_transaction
    elif payconiq_transaction_finished(transaction.test_mode, transaction.payconic_transaction_id, headers):
  File "/base/data/home/apps/e~rogerthat-server/20180518t124001.409804319394300144/rogerthat/bizz/payment/providers/payconiq/api.py", line 407, in payconiq_transaction_finished
    url = ('https://dev.payconiq.com' if test_mode else 'https://payconiq.com') + '/v2/transactions/' + transaction_id
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by RubenMattan** [comment] 2018-05-23 12:31
Occurred because there was an 404 from payconiq, then the second time Bart pressed pay there was no payconiq transaction id

**Comment by RubenMattan** [comment] 2018-05-23 12:31
The 404 is caused by calling 'https://payconiq.com' instead of 'https://api.payconiq.com'

**Comment by RubenMattan** [comment] 2018-05-23 12:33
However we should improve the way we handle this

**Comment by RubenMattan** [comment] 2018-05-23 13:03
Fixed in https://github.com/rogerthat-platform/rogerthat-backend/commit/5b9970488b26a0c2fb58bd494a8239481c1e7e69

**Closed by RubenMattan** 2018-05-23 13:03 UTC
Labels: priority_major, type_bug
