### ISSUE TITLE
Make sure user is not empty when granting service role

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#78] opened 2017-02-01 07:03 UTC
Make sure `app_user_email` is not empty when sending the request

[XX-OFFLOADv1] {"function":"/mobi/rest/service/roles/grant","request_data":{"identity":"+default+", "app_user_email":"", "role_id":5707702298738688}, "success":false, "timestamp":1485886177, "response_data":"", "type":"web", "user":"e50458283bf716dc3cfde97a6b2920e9"}

```
E 19:09:37.873

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/8.398856891300226802/mcfw/restapi.py", line 156, in post
    result = self.run(f, parameters, kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/8.398856891300226802/mcfw/restapi.py", line 174, in run
    result = run(f, kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/8.398856891300226802/mcfw/rpc.py", line 165, in run
    result = function(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/8.398856891300226802/mcfw/restapi.py", line 70, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/8.398856891300226802/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/8.398856891300226802/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/8.398856891300226802/rogerthat/restapi/service_panel.py", line 316, in grant_service_role
    app_user = create_app_user_by_email(*app_user_email.rsplit(':', 1))
  File "/base/data/home/apps/s~mobicagecloudhr/8.398856891300226802/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/8.398856891300226802/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/8.398856891300226802/rogerthat/utils/app.py", line 72, in create_app_user_by_email
    return users.User(human_user_email)
  File "/base/data/home/apps/s~mobicagecloudhr/8.398856891300226802/add_1_monkey_patches.py", line 66, in __init__
    original_constructor(self, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/users.py", line 123, in __init__
    raise UserNotFoundError
UserNotFoundError
```

**Comment by RubenMattan** [comment] 2017-03-31 08:12
duplicate of #107

**Closed by RubenMattan** 2017-03-31 08:12 UTC
Labels: priority_minor, type_bug
