### ISSUE TITLE
There are double service logs in case of an unknown exception

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#347] opened 2017-11-28 09:24 UTC
![screen shot 2017-11-28 at 10 23 29](https://user-images.githubusercontent.com/17762105/33311815-417f19ce-d426-11e7-8968-c7db2fd4d5c9.png)

**Comment by RubenMattan** [comment] 2018-02-01 11:43
duplicate of #92

**Closed** 2018-02-01 11:43 UTC
Labels: priority_minor, process_duplicate, type_bug
