### ISSUE TITLE
Would be handy if admin service can set the name for the user

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#256] opened 2017-08-17 08:56 UTC
For example as response of `friend.register` would be enough for now. If there's OAUTH based registration, the service could get the user's name and set it as name for the rogerthat user.

**Comment by RubenMattan** [comment] 2017-11-07 07:51
duplicate of https://github.com/rogerthat-platform/rogerthat-backend/issues/325

**Closed by RubenMattan** 2017-11-07 07:51 UTC
Labels: type_feature
