### ISSUE TITLE
Error in logs in mdp module

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#86] opened 2017-02-06 14:55 UTC
```
12:43:24.581
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/app_logging.py", line 78, in emit
    self.format(record),
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 25: ordinal not in range(128)
Logged from file mdp.py, line 161
```

**Comment by RubenMattan** [comment] 2017-03-31 08:17
duplicate of #72

**Closed by RubenMattan** 2017-03-31 08:17 UTC
Labels: process_duplicate, type_bug
