### ISSUE TITLE
Failed to get flow statistics in excel format

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-backend#46] opened 2016-12-08 10:02 UTC
```python

09:25:56.622
FileObject 'templates/img/osa_white_nl_250.jpg', Basepath: '/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/solutions/common'
09:25:56.623
URLParts: ParseResult(scheme='', netloc='', path='/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/solutions/common', params='', query='', fragment='')
09:26:11.431
Loaded timezone from memcache: pytz.zoneinfo.2010h.Europe/Brussels
09:26:12.214
skipping flow statistics with tag Ambrosiana: verkeersmaatregelen (sheet name problem)
Traceback (most recent call last):
  File "/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/rogerthat/bizz/service/statistics.py", line 217, in get_flow_statistics_excel
    messages_sheet = book.add_sheet(sheet_name)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/lib/xlwt.zip/xlwt/Workbook.py", line 328, in add_sheet
    raise Exception("invalid worksheet name %r" % sheetname)
Exception: invalid worksheet name u'Ambrosiana: Verkeersmaatregelen'
09:35:54.537

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/rogerthat/wsgi/__init__.py", line 84, in __call__
    return run_in_context(self._call_in_context, environ, start_response, _path=environ['PATH_INFO'])
  File "/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/rogerthat/rpc/context.py", line 54, in run_in_context
    return f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/rogerthat/wsgi/__init__.py", line 110, in _call_in_context
    return webapp2.WSGIApplication.__call__(self, environ, start_response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/add_1_monkey_patches.py", line 270, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/solutions/common/bizz/inbox.py", line 450, in _deferred_statistics_email_export
    flow_statistics_excel = base64.b64decode(system.export_flow_statistics(service_identity))
  File "/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/rogerthat/rpc/service.py", line 312, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/rogerthat/service/api/system.py", line 493, in export_flow_statistics
    return base64.b64encode(get_flow_statistics_excel(service_identity_user))
  File "/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/rogerthat/bizz/service/statistics.py", line 191, in get_flow_statistics_excel
    models = qry.fetch(50)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 2161, in fetch
    return list(self.run(limit=limit, offset=offset, **kwargs))
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 2330, in next
    return self.__model_class.from_entity(self.__iterator.next())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 1445, in from_entity
    return cls(None, _from_entity=entity, **entity_values)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 1835, in __init__
    setattr(self, prop, value)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/rogerthat/models/__init__.py", line 2429, in __setattr__
    value = db.Blob(str(CompressedIntegerList(value, self, name)))
  File "/base/data/home/apps/s~mobicagecloudhr/1.397586285257874813/rogerthat/models/properties/__init__.py", line 62, in __str__
    return zlib.compress(stream.getvalue())
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/contextlib.py", line 153, in __exit__
    def __exit__(self, *exc_info):
DeadlineExceededError: The overall deadline for responding to the HTTP request was exceeded.
```

**Comment by abom** [comment] 2016-12-08 12:52
Sheet name shouldn't have ":", it is validated with https://github.com/python-excel/xlwt/blob/917a8ad8db35d6e8abb306a2fda2ace648a6ab89/xlwt/Utils.py#L155

We may replace any of the invalid characters i think:
`u"[]:\\?/*\x00"`

**Comment by RubenMattan** [comment] 2016-12-08 15:46
@FastGeert  @bart-at-mobicage 

It takes more then 10 minutes to generate an email export
```python
try:
        messages_pdf, message_statistics_excel = export_inbox_messages(service_user, service_identity)
        broadcast_statistics = get_broadcast_statistics_excel(service_user, service_identity)
        flow_statistics_excel = base64.b64decode(system.export_flow_statistics(service_identity))
    finally:
        users.clear_user()
```

**Comment by FastGeert** [comment] 2016-12-08 16:43
@RubenMattan please analyse which step is so slow!

**Comment by RubenMattan** [comment] 2016-12-09 07:56
1. 12s
2. 0s
3. timeout ....

**Comment by RubenMattan** [comment] 2016-12-12 07:37
Probably by sending a broadcast from the service panels without a tag

**Comment by RubenMattan** [comment] 2016-12-13 10:57
Can't get the mfr running...

**Comment by bart-at-mobicage** [comment] 2016-12-23 14:38
It looks like this was fixed in MFR at May 06 2016. I think the problem is that the FlowStats before this day are not reconstructed/deleted. I'm waiting for Lochristi's decision about those stats.

**Comment by bart-at-mobicage** [comment] 2016-12-30 08:42
The broken FlowStatistics can be removed (those with a MFR MemberRun db.Key as tag)

**Closed** 2017-02-01 07:06 UTC
Labels: priority_minor, state_verification, type_bug
